### ISSUE TITLE
Support storing repositories in config

### ISSUE THREAD

**Issue by GavinF17** [git-jock/git-jock-cli#110]
Add support for storing named repositories in a config file at `$HOME/.jockrc`

This should allow repositories to be named, and store their git address and local location (absolute or relative to the rc file), e.g.
```yaml
repositories:
  - name: auth-service
    address: git@github.com:some-startup/authentication-service.git
    directory: ~/git/authentication-service
  - name: shared-entities
    address: git@github.com:some-startup/shared-entities.git
    directory: ../shared-entities
  - ...
  - name: user-service
    address: git@github.com:some-startup/user-service.git
    directory: /home/gavin/users
```

These will be invoked using`--repository NAME`, taking over from the current adjacent directory behaviour.
