### ISSUE TITLE
Support grouping repos in config

### ISSUE THREAD

**Issue by GavinF17** [git-jock/git-jock-cli#113]
Support groups within the .jockrc config file, which can then be used in place of separate `--respository`s within commands.

```yaml
repositories:
  auth-service:
    address: git@github.com:some-startup/authentication-service.git
    directory: ~/git/authentication-service
  shared-entities:
    address: git@github.com:some-startup/shared-entities.git
    directory: ../shared-entities
  - ...
  user-service:
    address: git@github.com:some-startup/user-service.git
    directory: /home/gavin/users
groups:
  services:
    repositories:
      - auth-service
      - user-service
  libraries:
    repositories:
      - shared-entities
```

Note the repos should be held in a child field rather than being directly under the group name, this is to allow other fields to be added in future, e.g. aliases

`jock --group services pull`
