### ISSUE TITLE
README incorrect on group usage

### ISSUE THREAD

**Issue by GavinF17** [git-jock/git-jock-cli#121]
The current example config yaml displays the groups as an array, whereas it should be a map, i.e.

```yaml
groups:
  - name: services
    repositories:
      - auth-service
      - user-service
```
should be
```yaml
groups:
  services:
    repositories:
      - auth-service
      - user-service
```
